### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by kaelzhang** [BigFaceWangCY/numberComputedAsString#3]
- [x] remove and ignore package-lock.json which is for applications but NOT libraries
- [x] remove and ignore built dest files. NEVER include them for git.
- [x] use npm `package.files` field to include ts sources, es sources and cjs sources for npm tarball
- [x] run tests on [travis-ci](https://travis-ci.org/), add travis badge in README.md
- [x] run coverage tests and improve your test spec to reach coverage 100%
- [x] report coverage to [codecov](https://codecov.io/), and add codecov badge in README.md
- [x] do not populate the exports to `window` object, which is the duty of [umd](https://github.com/umdjs/umd).

**Comment by jincan39** [comment]
good job, it would be nicer if:
- [ ]  bigInt support in chrome https://developers.google.com/web/updates/2018/05/bigint
- [x]  benchmark test

**Comment by BigFaceWangCY** [comment]
done
